# Generated by Django 3.1.4 on 2020-12-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('augielist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_price', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('post_email', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='augielist_app.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='cohort',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
